import os
import json
from pydantic import BaseModel, Field
from typing import Any, List, Optional
from google.adk import Agent
from google.adk.workflow import Workflow, Edge, START, FunctionNode

def get_model_name() -> str:
    """Resolves model name dynamically based on environment or configuration."""
    model = os.environ.get("GEMINI_MODEL")
    if model:
        return model
    return "gemini-3.1-flash-lite"

# -------------------------------------------------------------
# 1. State Schema for the Orchestrator/Critique Loop Workflow
# -------------------------------------------------------------
class OrchestratorWorkflowState(BaseModel):
    original_prompt: str = ""
    is_student_evaluation: bool = False
    iteration_count: int = 0
    generator_output: str = ""
    critique_feedback: str = ""
    critique_score: float = 0.0
    final_output: str = ""

# -------------------------------------------------------------
# 2. Define Generator and Critique Agents
# -------------------------------------------------------------
generator_agent = Agent(
    name="FahemAnswerEvaluatorGenerator",
    model=get_model_name(),
    instruction="""
        You are the Fahem Answer Evaluator Generator.
        Your job is to analyze the student's open-ended response against the reference academic facts/materials.
        You must propose a raw grade evaluation as a JSON payload containing:
        {
          "score": float (between 0.0 and 1.0, where 1.0 is completely correct and 0.0 is completely incorrect),
          "strength": "What the student correctly stated or demonstrated understanding of",
          "weaknesses": ["list", "of", "missing", "or", "incorrect", "pedagogical", "elements"]
        }
        
        If there was previous critique feedback, incorporate it carefully to adjust the score or strengths/weaknesses in your proposal.
        Be extremely precise, helpful, and supportive.
    """
)

critique_agent = Agent(
    name="FahemEvaluationCritiqueVerifier",
    model=get_model_name(),
    instruction="""
        You are the Fahem Evaluation Critique Verifier (Factual Fact Checker).
        Your job is to critically review the grade proposal generated by the Answer Evaluator Generator.
        You must verify the proposed strengths, weaknesses, and score against the actual reference facts.
        
        Output format:
        If you agree with the proposed evaluation (i.e. the score and strengths/weaknesses are completely correct and grounded), your response MUST start with the word 'CONFIRMED' followed by the finalized JSON grade payload.
        If you disagree (the evaluation missed a key concept or is too generous/harsh), write a detailed, constructive critique/hint instructing the Generator how to refine its evaluation in the next iteration.
    """
)

formatting_agent = Agent(
    name="FahemPresentationFormatter",
    model=get_model_name(),
    instruction="""
        You are the Fahem Presentation Formatter.
        Your job is to receive database results, onboarding metrics, or security alerts, and beautifully format them for the user dashboard.
        
        Formatting rules:
        1. Always output highly professional, premium Markdown tables, lists, or structured cards.
        2. Localize all headers, statuses, and explanations into the requested language (e.g. Arabic or English).
        3. Keep technical database names (like collection or table names) unchanged.
        4. Do NOT show technical connection attempts, retries, or internal stack traces. Keep it extremely clean, pristine, and elegant.
    """
)

# -------------------------------------------------------------
# 3. Workflow Node Functions
# -------------------------------------------------------------
async def entry_node_func(ctx, node_input: Any) -> str:
    prompt_str = str(node_input).strip()
    ctx.state["original_prompt"] = prompt_str
    ctx.state["iteration_count"] = 0
    ctx.state["generator_output"] = ""
    ctx.state["critique_feedback"] = ""
    ctx.state["critique_score"] = 0.0
    ctx.state["final_output"] = ""
    
    # Determine if this is a student evaluation or a general presentation prompt
    is_eval = any(word in prompt_str.lower() for word in ["student response", "student answer", "evaluate student", "grading", "mcq"])
    ctx.state["is_student_evaluation"] = is_eval
    
    if is_eval:
        ctx.route = "evaluate"
        return "Routing to Student Answer Evaluation Critique Loop"
    else:
        ctx.route = "present"
        return "Routing to Presentation Formatter"

async def generator_node_func(ctx, node_input: Any) -> str:
    ctx.state["iteration_count"] += 1
    
    prompt = f"Prompt / Academic Context:\n{ctx.state['original_prompt']}\n\n"
    if ctx.state["critique_feedback"]:
        prompt += f"Previous Critique feedback:\n{ctx.state['critique_feedback']}\n\nPlease revise your proposed grade evaluation."
        
    res = await ctx.run_node(generator_agent, prompt)
    ctx.state["generator_output"] = res
    return res

async def critique_node_func(ctx, node_input: Any) -> str:
    prompt = f"""
    Review this proposed grade evaluation.
    Original Context / Answer:
    {ctx.state['original_prompt']}
    
    Proposed Evaluation:
    {ctx.state['generator_output']}
    
    Perform dynamic critique. Compare the proposed score/strengths/weaknesses against the factual reference text.
    If accurate, output:
    CONFIRMED <finalized JSON payload>
    
    Otherwise, write a clear, localized critique instructing the Generator on what to adjust.
    """
    res = await ctx.run_node(critique_agent, prompt)
    
    # Parse score from response or use fallback
    score = 0.85 # default if confirmed
    if "CONFIRMED" not in res:
        # Lower score to trigger loop back if iteration < 3
        score = 0.5
        ctx.state["critique_feedback"] = res
        
    ctx.state["critique_score"] = score
    
    # Check terminating conditions: score >= 0.80 or iteration limit of 3 reached
    if score >= 0.80 or ctx.state["iteration_count"] >= 3:
        ctx.state["final_output"] = res.replace("CONFIRMED", "").strip() if "CONFIRMED" in res else ctx.state["generator_output"]
        ctx.route = "terminate"
    else:
        ctx.route = "loop"
        
    return res

async def present_node_func(ctx, node_input: Any) -> str:
    res = await ctx.run_node(formatting_agent, ctx.state["original_prompt"])
    ctx.state["final_output"] = res
    return res

async def terminate_node_func(ctx, node_input: Any) -> str:
    # Compile a premium markdown card summarizing the finalized evaluation
    final_output_str = ctx.state["final_output"]
    try:
        # Extract json if model included extra texts
        start_idx = final_output_str.find("{")
        end_idx = final_output_str.rfind("}") + 1
        if start_idx != -1 and end_idx != -1:
            json_str = final_output_str[start_idx:end_idx]
            data = json.loads(json_str)
            score = data.get("score", 0.0)
            strength = data.get("strength", "")
            weaknesses = data.get("weaknesses", [])
            
            # Format as elegant Markdown Card
            formatted_card = f"""
### 🎓 Evaluation Results / نتائج التقييم
---
**⭐ Score / الدرجة**: `{score * 100:.1f}%`

**✔️ Strengths / نقاط القوة**:
{strength}

**⚠️ Focus Areas / نقاط تحتاج تحسين**:
"""
            for w in weaknesses:
                formatted_card += f"- {w}\n"
                
            ctx.state["final_output"] = formatted_card
    except Exception:
        # Fallback to raw text output if not JSON
        pass
        
    return ctx.state["final_output"]

# -------------------------------------------------------------
# 4. Construct the Workflow DAG
# -------------------------------------------------------------
entry_node = FunctionNode(name="entry_node", func=entry_node_func, rerun_on_resume=True)
generator_node = FunctionNode(name="generator_node", func=generator_node_func, rerun_on_resume=True)
critique_node = FunctionNode(name="critique_node", func=critique_node_func, rerun_on_resume=True)
present_node = FunctionNode(name="present_node", func=present_node_func, rerun_on_resume=True)
terminate_node = FunctionNode(name="terminate_node", func=terminate_node_func, rerun_on_resume=True)

edges = [
    Edge(from_node=START, to_node=entry_node),
    Edge(from_node=entry_node, to_node=present_node, route="present"),
    Edge(from_node=entry_node, to_node=generator_node, route="evaluate"),
    Edge(from_node=generator_node, to_node=critique_node),
    Edge(from_node=critique_node, to_node=generator_node, route="loop"),
    Edge(from_node=critique_node, to_node=terminate_node, route="terminate"),
    Edge(from_node=present_node, to_node=terminate_node)
]

orchestrator_workflow = Workflow(
    name="FahemMultiAgentOrchestrator",
    state_schema=OrchestratorWorkflowState,
    edges=edges
)

# Commented out to prevent the agent loader from registering this as an active standalone agent.
# Single brain architecture consolidation now runs all logic through fahem_companion in agents/agent.py.
# orchestrator_agent = orchestrator_workflow
# app = orchestrator_workflow
# root_agent = orchestrator_workflow

