const fs = require('fs');
const path = require('path');

const dictDir = path.join(__dirname, '..', 'src', 'dictionaries');

const translationsToInject = {
  en: {
    "nav_terms": "Terms of Service",
    "nav_privacy": "Privacy Policy",
    "nav_report": "Submit Report",
    "terms_title": "Terms of Service & Agreements",
    "terms_subtitle": "Terms, conditions, and artificial intelligence usage guidelines for Fahem.",
    "privacy_title": "Privacy Policy",
    "privacy_subtitle": "Your data privacy, processing, and security guidelines.",
    "ai_disclaimer_title": "AI & Large Language Model Disclaimer",
    "ai_disclaimer_text": "Fahem leverages Google Gemini AI models and MongoDB Model Context Protocol (MCP) servers to analyze schemas, view statistics, and run queries programmatically. While the assistant is highly capable, all database manipulations, recommendations, and execution plans generated by the AI are provided 'as-is' without warranties. Users should review and verify critical statements, schema transformations, and direct queries prior to execution in production environments.",
    "report_tool_title": "Submit a Database / Agent Report",
    "report_tool_desc": "Report an issue, bug, or submit database feedback. Your report will be processed directly by our secure MongoDB Agent.",
    "lbl_report_name": "Full Name",
    "lbl_report_email": "Email Address",
    "lbl_report_subject": "Subject / Issue Type",
    "lbl_report_description": "Detailed Report / Feedback",
    "btn_submit_report": "Submit Report",
    "report_success": "Your report was successfully ingested into MongoDB via the MCP Agent!",
    "social_follow": "Follow us on social media"
  },
  ar: {
    "nav_terms": "شروط الخدمة",
    "nav_privacy": "سياسة الخصوصية",
    "nav_report": "تقديم تقرير",
    "terms_title": "شروط الخدمة والاتفاقيات",
    "terms_subtitle": "الشروط والأحكام وإرشادات استخدام الذكاء الاصطناعي لمنصة فهم.",
    "privacy_title": "سياسة الخصوصية",
    "privacy_subtitle": "إرشادات خصوصية البيانات ومعالجتها وأمانها لدينا.",
    "ai_disclaimer_title": "إخلاء مسؤولية الذكاء الاصطناعي والنماذج اللغوية الكبيرة",
    "ai_disclaimer_text": "تستخدم منصة فهم نماذج الذكاء الاصطناعي Google Gemini وخوادم بروتوكول سياق نموذج (MCP) لـ MongoDB لتحليل المخططات وعرض الإحصاءات وتشغيل الاستعلامات برمجياً. على الرغم من الكفاءة العالية للمساعد، فإن جميع معالجات قواعد البيانات والتوصيات وخطط التنفيذ التي تم إنشاؤها بواسطة الذكاء الاصطناعي تُقدم 'كما هي' دون أي ضمانات. يجب على المستخدمين مراجعة التحولات الهيكلية والاستعلامات المباشرة والتحقق منها قبل تنفيذها في بيئات الإنتاج الفعلي.",
    "report_tool_title": "تقديم تقرير عن قاعدة البيانات / الوكيل",
    "report_tool_desc": "أبلغ عن مشكلة أو خطأ أو أرسل ملاحظاتك. سيتم معالجة تقريرك مباشرة بواسطة وكيل MongoDB الآمن لدينا.",
    "lbl_report_name": "الاسم الكامل",
    "lbl_report_email": "البريد الإلكتروني",
    "lbl_report_subject": "الموضوع / نوع المشكلة",
    "lbl_report_description": "تقرير مفصل / الملاحظات",
    "btn_submit_report": "تقديم التقرير",
    "report_success": "تم إدخال تقريرك بنجاح في قاعدة بيانات MongoDB عبر وكيل MCP!",
    "social_follow": "تابعنا على وسائل التواصل الاجتماعي"
  },
  de: {
    "nav_terms": "Nutzungsbedingungen",
    "nav_privacy": "Datenschutzerklärung",
    "nav_report": "Bericht senden",
    "terms_title": "Nutzungsbedingungen & Vereinbarungen",
    "terms_subtitle": "Geschäftsbedingungen und Richtlinien zur Nutzung künstlicher Intelligenz für Fahem.",
    "privacy_title": "Datenschutzerklärung",
    "privacy_subtitle": "Richtlinien zu Datenschutz, Verarbeitung und Sicherheit Ihrer Daten.",
    "ai_disclaimer_title": "Haftungsausschluss für KI & große Sprachmodelle",
    "ai_disclaimer_text": "Fahem nutzt Google Gemini-KI-Modelle und MongoDB Model Context Protocol (MCP)-Server, um Schemata zu analysieren, Statistiken anzuzeigen und Abfragen programmgesteuert auszuführen. Obwohl der Assistent äußerst leistungsfähig ist, werden alle von der KI generierten Datenbankmanipulationen, Empfehlungen und Ausführungspläne ohne Mängelgewähr zur Verfügung gestellt. Benutzer sollten kritische Aussagen, Schematransformationen und direkte Abfragen vor der Ausführung in Produktionsumgebungen überprüfen.",
    "report_tool_title": "Einen Datenbank- / Agentenbericht senden",
    "report_tool_desc": "Melden Sie ein Problem, einen Fehler oder geben Sie Feedback zur Datenbank. Ihr Bericht wird direkt von unserem sicheren MongoDB-Agenten verarbeitet.",
    "lbl_report_name": "Vollständiger Name",
    "lbl_report_email": "E-Mail-Adresse",
    "lbl_report_subject": "Betreff / Art des Problems",
    "lbl_report_description": "Detaillierter Bericht / Feedback",
    "btn_submit_report": "Bericht einreichen",
    "report_success": "Ihr Bericht wurde erfolgreich über den MCP-Agenten in MongoDB erfasst!",
    "social_follow": "Folgen Sie uns in den sozialen Medien"
  },
  es: {
    "nav_terms": "Términos de Servicio",
    "nav_privacy": "Política de Privacidad",
    "nav_report": "Enviar Reporte",
    "terms_title": "Términos de Servicio y Acuerdos",
    "terms_subtitle": "Términos, condiciones y pautas de uso de inteligencia artificial para Fahem.",
    "privacy_title": "Política de Privacidad",
    "privacy_subtitle": "Pautas de privacidad, procesamiento y seguridad de sus datos.",
    "ai_disclaimer_title": "Descargo de Responsabilidad de IA y Modelos de Lenguaje Grandes",
    "ai_disclaimer_text": "Fahem aprovecha los modelos de IA de Google Gemini y los servidores MongoDB Model Context Protocol (MCP) para analizar esquemas, ver estadísticas y ejecutar consultas mediante programación. Si bien el asistente es altamente competente, todas las manipulaciones de bases de datos, recomendaciones y planes de ejecución generados por la IA se proporcionan 'tal cual' sin garantías. Los usuarios deben revisar y verificar las declaraciones críticas, las transformaciones de esquemas y las consultas directas antes de la ejecución en entornos de producción.",
    "report_tool_title": "Enviar un Reporte de Base de Datos / Agente",
    "report_tool_desc": "Reporte un problema, error o envíe comentarios sobre la base de datos. Su reporte será procesado directamente por nuestro agente seguro de MongoDB.",
    "lbl_report_name": "Nombre Completo",
    "lbl_report_email": "Correo Electrónico",
    "lbl_report_subject": "Asunto / Tipo de Problema",
    "lbl_report_description": "Reporte Detallado / Comentarios",
    "btn_submit_report": "Enviar Reporte",
    "report_success": "¡Su reporte se ingresó con éxito en MongoDB a través del Agente MCP!",
    "social_follow": "Síguenos en las redes sociales"
  },
  fr: {
    "nav_terms": "Conditions d'utilisation",
    "nav_privacy": "Politique de confidentialité",
    "nav_report": "Soumettre un rapport",
    "terms_title": "Conditions d'utilisation et accords",
    "terms_subtitle": "Conditions, règles et directives d'utilisation de l'intelligence artificielle pour Fahem.",
    "privacy_title": "Politique de confidentialité",
    "privacy_subtitle": "Directives sur la confidentialité, le traitement et la sécurité de vos données.",
    "ai_disclaimer_title": "Clause de non-responsabilité relative à l'IA et aux grands modèles de langage",
    "ai_disclaimer_text": "Fahem utilise les modèles d'IA Google Gemini et les serveurs MongoDB Model Context Protocol (MCP) pour analyser les schémas, afficher les statistiques et exécuter des requêtes par programmation. Bien que l'assistant soit extrêmement compétent, toutes les manipulations de base de données, recommandations et plans d'exécution générés par l'IA sont fournis 'en l'état' sans garantie. Les utilisateurs doivent examiner et vérifier les instructions critiques, les transformations de schéma et les requêtes directes avant de les exécuter dans des environnements de production.",
    "report_tool_title": "Soumettre un rapport de base de données / d'agent",
    "report_tool_desc": "Signalez un problème, un bogue ou soumettez des commentaires sur la base de données. Votre rapport sera traité directement par notre agent MongoDB sécurisé.",
    "lbl_report_name": "Nom complet",
    "lbl_report_email": "Adresse e-mail",
    "lbl_report_subject": "Sujet / Type de problème",
    "lbl_report_description": "Rapport détaillé / Commentaires",
    "btn_submit_report": "Soumettre le rapport",
    "report_success": "Votre rapport a été enregistré avec succès dans MongoDB via l'agent MCP !",
    "social_follow": "Suivez-nous sur les réseaux sociaux"
  },
  it: {
    "nav_terms": "Termini di Servizio",
    "nav_privacy": "Informativa sulla Privacy",
    "nav_report": "Invia Segnalazione",
    "terms_title": "Termini di Servizio e Accordi",
    "terms_subtitle": "Termini, condizioni e linee guida sull'uso dell'intelligenza artificiale per Fahem.",
    "privacy_title": "Informativa sulla Privacy",
    "privacy_subtitle": "Linee guida sulla privacy, elaborazione e sicurezza dei tuoi dati.",
    "ai_disclaimer_title": "Esclusione di responsabilità per IA e modelli linguistici di grandi dimensioni",
    "ai_disclaimer_text": "Fahem sfrutta i modelli IA Google Gemini e i server MongoDB Model Context Protocol (MCP) per analizzare schemi, visualizzare statistiche ed eseguire query in modo programmatico. Sebbene l'assistente sia altamente capace, tutte le manipolazioni del database, le raccomandazioni e i piani di esecuzione generati dall'IA vengono forniti 'così come sono' senza garanzie. Gli utenti devono rivedere e verificare le dichiarazioni critiche, las trasformazioni dello schema e le query dirette prima dell'esecuzione in ambienti di produzione.",
    "report_tool_title": "Invia una segnalazione sul database / agente",
    "report_tool_desc": "Segnala un problema, un bug o invia un feedback sul database. La tua segnalazione sarà elaborata direttamente dal nostro agente MongoDB sicuro.",
    "lbl_report_name": "Nome completo",
    "lbl_report_email": "Indirizzo e-mail",
    "lbl_report_subject": "Oggetto / Tipo di problema",
    "lbl_report_description": "Segnalazione dettagliata / Feedback",
    "btn_submit_report": "Invia Segnalazione",
    "report_success": "La tua segnalazione è stata inserita con successo nel MongoDB tramite l'Agente MCP!",
    "social_follow": "Seguici sui social media"
  },
  zh: {
    "nav_terms": "服务条款",
    "nav_privacy": "隐私政策",
    "nav_report": "提交报告",
    "terms_title": "服务条款与协议",
    "terms_subtitle": "Fahem 的条款、条件和人工智能使用指南。",
    "privacy_title": "隐私政策",
    "privacy_subtitle": "您的数据隐私、处理和安全准则。",
    "ai_disclaimer_title": "人工智能与大语言模型免责声明",
    "ai_disclaimer_text": "Fahem 利用 Google Gemini AI 模型和 MongoDB 模型上下文协议 (MCP) 服务器，以编程方式模式分析、查看统计数据并运行查询。虽然助手功能强大，但人工智能生成的所有数据库操作、建议和执行计划均按“原样”提供，不作任何保证。用户在生产环境中执行之前，应审查并验证关键语句、模式转换和直接查询。",
    "report_tool_title": "提交数据库 / 代理报告",
    "report_tool_desc": "报告问题、缺陷或提交数据库反馈。您的报告将由我们的安全 MongoDB 代理直接处理。",
    "lbl_report_name": "姓名",
    "lbl_report_email": "电子邮件地址",
    "lbl_report_subject": "主题 / 问题类型",
    "lbl_report_description": "详细报告 / 反馈",
    "btn_submit_report": "提交报告",
    "report_success": "您的报告已通过 MCP 代理成功录入 MongoDB！",
    "social_follow": "在社交媒体上关注我们"
  }
};

for (const [lang, translations] of Object.entries(translationsToInject)) {
  const filePath = path.join(dictDir, `${lang}.json`);
  if (fs.existsSync(filePath)) {
    try {
      const data = JSON.parse(fs.readFileSync(filePath, 'utf8'));
      const updated = { ...data, ...translations };
      fs.writeFileSync(filePath, JSON.stringify(updated, null, 2), 'utf8');
      console.log(`Successfully patched ${lang}.json`);
    } catch (e) {
      console.error(`Error patching ${lang}.json:`, e);
    }
  } else {
    console.warn(`File ${lang}.json does not exist.`);
  }
}
