"use client";

import React, { createContext, useContext, useState, useEffect } from "react";

export type Language = "en" | "ar" | "es" | "fr" | "de" | "zh" | "it";

export interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  dir: "ltr" | "rtl";
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    nav_overview: "Overview",
    nav_toolkit: "Agent Toolkit",
    nav_github: "GitHub",
    nav_signin: "Sign In",
    nav_signing_in: "Signing In...",
    welcome_to_fahem: "Welcome to Fahem",
    hero_subtitle: "An intelligent AI assistant console programmatically powered by the Google Agent Development Kit (ADK) and MongoDB MCP toolsets.",
    bullet_1: "Exposes custom MongoDB Schema wrappers",
    bullet_2: "Pipes real-time execution logs from Python ADK",
    bullet_3: "Fully sandboxed and secure database diagnostics",
    btn_signin_google: "Sign in with Google",
    btn_connecting_google: "Connecting to Google...",
    footer_landing: "Fahem Project Console • Google Cloud Rapid Agent Hackathon",
    loading_ambient: "Loading ambient environment...",
    loading_session: "Verifying session...",
    dashboard_title: "Fahem",
    dashboard_subtitle: "Google ADK & MongoDB MCP Assistant Console",
    btn_signout: "Sign Out",
    cluster_status: "MongoDB Atlas Cluster: Connected",
    ask_agent_header: "Ask the MongoDB Agent",
    btn_execute: "Execute Agent",
    btn_executing: "Streaming Output...",
    btn_clear: "Clear",
    input_placeholder: "Enter a custom database request (e.g. 'Analyze collections and show stats for fahem database')",
    logs_header: "Execution Stream Logs",
    logs_idle: "Console idle. Awaiting command execution...",
    agent_response_header: "Agent Response:",
    metadata_header: "Cluster Metadata",
    meta_active_db: "Active Database",
    meta_collections: "Collections",
    meta_col_names: "Collection Names",
    meta_storage_size: "Storage Size",
    config_header: "Agent Core Config",
    config_model: "Gemini Model:",
    config_framework: "Orchestrator Framework:",
    config_mcp: "MCP Connection:",
    config_tools: "Exposed Tools:",
    footer_dashboard_line1: "Fahem Console Dashboard | Hackathon MongoDB Track Partner Integration",
    footer_dashboard_line2: "Running on Firebase App Hosting • Secure Google Cloud Secret Manager Environment",
    preset_list_db_title: "List Databases",
    preset_list_db_desc: "Discovers all available databases and lists their basic metrics.",
    preset_get_stats_title: "Get Database Stats",
    preset_get_stats_desc: "Retrieves storage size, index counts, and document stats for 'fahem'.",
    preset_schema_title: "Analyze Schema",
    preset_schema_desc: "Samples documents from 'users' collection to derive its schema.",
    preset_list_col_title: "List Collections",
    preset_list_col_desc: "Lists all collections in the 'fahem' database.",
    nav_admin: "Admin Panel",
    sourcing_engine_title: "Sourcing Engine",
    sourcing_engine_subtitle: "Configure database pipelines, ingest raw streams, and map document fields.",
    lbl_pipeline_name: "Pipeline Name",
    pipeline_name_placeholder: "e.g. User Logs Feed",
    lbl_ingestion_url: "Ingestion URL / Feed Endpoint",
    ingestion_url_placeholder: "e.g. https://api.fahem.app/v1/sourcing-feed",
    lbl_target_collection: "Target Collection",
    lbl_pipeline_schedule: "Pipeline Schedule",
    schedule_realtime: "Real-time Stream",
    schedule_hourly: "Hourly Sync",
    schedule_daily: "Daily Batch",
    schedule_manual: "Manual Trigger",
    btn_create_pipeline: "Create Pipeline Feed",
    btn_test_connection: "Test Endpoint Connection",
    active_feeds_title: "Active Ingestion Feeds",
    tbl_feed_name: "Feed Name",
    tbl_target_col: "Target Col",
    tbl_schedule: "Schedule",
    tbl_status: "Status",
    status_active: "Active",
    status_idle: "Idle",
    feed_user_activity: "User Activity Stream",
    feed_partner_sync: "Partner Database Sync",
    create_new_collection: "Create new collection...",
    config_tools_list: "MongoDB MCP Stdio Toolset",
    status_connecting: "Connecting...",
    status_error: "Error fetching metadata",
    status_disconnected: "Disconnected",
    auth_failed: "Authentication failed. Please try again.",
    initiating_stream: "[SYSTEM] Initiating agent execution stream...",
    query_completed_success: "Query completed successfully. Please check the logs console for output details.",
    stream_failure: "[ERROR] Stream failure: ",
    stream_error_occurred: "An error occurred while streaming the agent output: ",
    preset_list_db_query: "List the databases, list collections for 'fahem' database, and retrieve database stats.",
    preset_get_stats_query: "Analyze database statistics for the 'fahem' database and summarize storage size and index metrics.",
    preset_schema_query: "Get the collection schema for the 'users' collection inside the 'fahem' database and describe its fields.",
    preset_list_col_query: "List all collections present in the 'fahem' database."
  },
  ar: {
    nav_overview: "نظرة عامة",
    nav_toolkit: "أدوات الوكيل",
    nav_github: "جيت هاب",
    nav_signin: "تسجيل الدخول",
    nav_signing_in: "جاري الدخول...",
    welcome_to_fahem: "مرحباً بكم في فهم",
    hero_subtitle: "منصة ذكاء اصطناعي تفاعلية مدعومة برمجياً بحزمة تطوير الوكيل من جوجل (ADK) وأدوات بروتوكول سياق نموذج MongoDB (MCP).",
    bullet_1: "يعرض مغلفات مخصصة لمخطط قاعدة بيانات MongoDB",
    bullet_2: "ينقل سجلات التنفيذ الفورية من Python ADK مباشرة",
    bullet_3: "تشخيصات قاعدة بيانات معزولة تماماً وآمنة للغاية",
    btn_signin_google: "تسجيل الدخول باستخدام جوجل",
    btn_connecting_google: "جاري الاتصال بجوجل...",
    footer_landing: "لوحة تحكم مشروع فهم • هاكاثون وكلاء جوجل السحابي السريع",
    loading_ambient: "جاري تحميل البيئة التفاعلية...",
    loading_session: "جاري التحقق من الجلسة...",
    dashboard_title: "فهم",
    dashboard_subtitle: "لوحة تحكم مساعد جوجل ADK وقاعدة بيانات MongoDB MCP",
    btn_signout: "تسجيل الخروج",
    cluster_status: "عنقود MongoDB Atlas: متصل",
    ask_agent_header: "اسأل وكيل MongoDB",
    btn_execute: "تشغيل الوكيل",
    btn_executing: "جاري بث المخرجات...",
    btn_clear: "مسح",
    input_placeholder: "أدخل طلباً مخصصاً لقاعدة البيانات (مثال: 'حلل المجموعات واعرض الإحصائيات لقاعدة فهم')",
    logs_header: "سجلات بث التنفيذ الفوري",
    logs_idle: "منصة التحكم في حالة انتظار. في انتظار تشغيل الأوامر...",
    agent_response_header: "إجابة الوكيل:",
    metadata_header: "البيانات الوصفية للعنقود",
    meta_active_db: "قاعدة البيانات النشطة",
    meta_collections: "المجموعات",
    meta_col_names: "أسماء المجموعات",
    meta_storage_size: "حجم التخزين",
    config_header: "الإعدادات الأساسية للوكيل",
    config_model: "نموذج Gemini:",
    config_framework: "إطار عمل التنسيق:",
    config_mcp: "اتصال MCP:",
    config_tools: "الأدوات المعروضة:",
    footer_dashboard_line1: "لوحة تحكم فهم | تكامل شريك مسار MongoDB في الهاكاثون",
    footer_dashboard_line2: "يعمل على استضافة تطبيقات Firebase • بيئة آمنة لإدارة أسرار Google Cloud",
    preset_list_db_title: "سرد قواعد البيانات",
    preset_list_db_desc: "يكتشف جميع قواعد البيانات المتاحة ويعرض مقاييسها الأساسية.",
    preset_get_stats_title: "إحصائيات قاعدة البيانات",
    preset_get_stats_desc: "يسترجع حجم التخزين، وأعداد الفهارس، وإحصائيات المستندات لقاعدة 'فهم'.",
    preset_schema_title: "تحليل المخطط",
    preset_schema_desc: "يأخذ عينات من المستندات من مجموعة 'المستخدمين' لاستنتاج مخططها.",
    preset_list_col_title: "سرد المجموعات",
    preset_list_col_desc: "يسرد جميع المجموعات في قاعدة بيانات 'فهم'.",
    nav_admin: "لوحة الإدارة",
    sourcing_engine_title: "محرك جلب البيانات",
    sourcing_engine_subtitle: "إعداد خطوط نقل البيانات، استيراد البث المباشر، وتعيين حقول المستندات.",
    lbl_pipeline_name: "اسم خط نقل البيانات",
    pipeline_name_placeholder: "مثال: بث سجلات المستخدم",
    lbl_ingestion_url: "رابط استيراد البيانات / نهاية نقطة البث",
    ingestion_url_placeholder: "مثال: https://api.fahem.app/v1/sourcing-feed",
    lbl_target_collection: "المجموعة المستهدفة",
    lbl_pipeline_schedule: "جدولة خط نقل البيانات",
    schedule_realtime: "بث فوري مباشر",
    schedule_hourly: "مزامنة كل ساعة",
    schedule_daily: "دفعة يومية",
    schedule_manual: "تشغيل يدوي",
    btn_create_pipeline: "إنشاء خط نقل البيانات",
    btn_test_connection: "اختبار اتصال نقطة النهاية",
    active_feeds_title: "خطوط نقل البيانات النشطة",
    tbl_feed_name: "اسم البث",
    tbl_target_col: "المجموعة المستهدفة",
    tbl_schedule: "الجدولة",
    tbl_status: "الحالة",
    status_active: "نشط",
    status_idle: "خامل",
    feed_user_activity: "بث نشاط المستخدمين",
    feed_partner_sync: "مزامنة قاعدة بيانات الشريك",
    create_new_collection: "إنشاء مجموعة جديدة...",
    config_tools_list: "أدوات بروتوكول MongoDB MCP",
    status_connecting: "جاري الاتصال...",
    status_error: "خطأ في استيراد البيانات الوصفية",
    status_disconnected: "غير متصل",
    auth_failed: "فشل المصادقة. يرجى المحاولة مرة أخرى.",
    initiating_stream: "[النظام] جاري بدء بث تنفيذ الوكيل...",
    query_completed_success: "اكتمل الطلب بنجاح. يرجى التحقق من لوحة سجلات البث لمزيد من التفاصيل.",
    stream_failure: "[خطأ] فشل البث: ",
    stream_error_occurred: "حدث خطأ أثناء بث مخرجات الوكيل: ",
    preset_list_db_query: "اسرد قواعد البيانات، واسرد المجموعات لقاعدة بيانات 'fahem'، واسترجع إحصائيات قاعدة البيانات.",
    preset_get_stats_query: "حلل إحصائيات قاعدة البيانات لقاعدة 'fahem' ولخّص حجم التخزين ومقاييس الفهرسة.",
    preset_schema_query: "احصل على مخطط المجموعة لمجموعة 'users' داخل قاعدة بيانات 'fahem' واشرح حقولها.",
    preset_list_col_query: "اسرد جميع المجموعات الموجودة في قاعدة بيانات 'fahem'."
  },
  es: {
    nav_overview: "Resumen",
    nav_toolkit: "Herramientas",
    nav_github: "GitHub",
    nav_signin: "Iniciar Sesión",
    nav_signing_in: "Conectando...",
    welcome_to_fahem: "Bienvenido a Fahem",
    hero_subtitle: "Consola de asistente de IA inteligente potenciada programáticamente por Google Agent Development Kit (ADK) y MongoDB MCP.",
    bullet_1: "Expone contenedores de esquema personalizados de MongoDB",
    bullet_2: "Transmite registros de ejecución en tiempo real desde Python ADK",
    bullet_3: "Diagnósticos de base de datos seguros en entorno aislado",
    btn_signin_google: "Iniciar sesión con Google",
    btn_connecting_google: "Conectando a Google...",
    footer_landing: "Consola de Fahem • Google Cloud Rapid Agent Hackathon",
    loading_ambient: "Cargando entorno ambiental...",
    loading_session: "Verificando sesión...",
    dashboard_title: "Fahem",
    dashboard_subtitle: "Consola de Asistente Google ADK y MongoDB MCP",
    btn_signout: "Cerrar Sesión",
    cluster_status: "Clúster MongoDB Atlas: Conectado",
    ask_agent_header: "Pregunta al Agente MongoDB",
    btn_execute: "Ejecutar Agente",
    btn_executing: "Transmitiendo...",
    btn_clear: "Limpiar",
    input_placeholder: "Ingrese una solicitud personalizada (ej. 'Analizar colecciones y mostrar estadísticas')",
    logs_header: "Registros de Ejecución",
    logs_idle: "Consola inactiva. Esperando comandos...",
    agent_response_header: "Respuesta del Agente:",
    metadata_header: "Metadatos del Clúster",
    meta_active_db: "Base de Datos Activa",
    meta_collections: "Colecciones",
    meta_col_names: "Nombres de Colecciones",
    meta_storage_size: "Tamaño de Almacenamiento",
    config_header: "Configuración del Agente",
    config_model: "Modelo Gemini:",
    config_framework: "Marco de Orquestación:",
    config_mcp: "Conexión MCP:",
    config_tools: "Herramientas Expuestas:",
    footer_dashboard_line1: "Panel de Fahem | Integración del Socio del Track MongoDB",
    footer_dashboard_line2: "Ejecutándose en Firebase App Hosting • Entorno Seguro de GCP Secret Manager",
    preset_list_db_title: "Listar Bases de Datos",
    preset_list_db_desc: "Descubre las bases de datos disponibles y sus métricas básicas.",
    preset_get_stats_title: "Obtener Estadísticas",
    preset_get_stats_desc: "Recupera tamaño de almacenamiento, índices y estadísticas de 'fahem'.",
    preset_schema_title: "Analizar Esquema",
    preset_schema_desc: "Muestrea documentos de la colección 'users' para derivar su esquema.",
    preset_list_col_title: "Listar Colecciones",
    preset_list_col_desc: "Enumera todas las colecciones en la base de datos 'fahem'.",
    nav_admin: "Panel de Control",
    sourcing_engine_title: "Motor de Sourcing",
    sourcing_engine_subtitle: "Configure canalizaciones, ingiera flujos sin procesar y mapee campos.",
    lbl_pipeline_name: "Nombre del Pipeline",
    pipeline_name_placeholder: "ej. Canal de Registros de Usuario",
    lbl_ingestion_url: "URL de Ingesta / Endpoint del Canal",
    ingestion_url_placeholder: "ej. https://api.fahem.app/v1/sourcing-feed",
    lbl_target_collection: "Colección de Destino",
    lbl_pipeline_schedule: "Programación del Pipeline",
    schedule_realtime: "Flujo en Tiempo Real",
    schedule_hourly: "Sincronización Horaria",
    schedule_daily: "Lote Diario",
    schedule_manual: "Activación Manual",
    btn_create_pipeline: "Crear Canal de Pipeline",
    btn_test_connection: "Probar Conexión del Endpoint",
    active_feeds_title: "Canales de Ingesta Activos",
    tbl_feed_name: "Nombre del Canal",
    tbl_target_col: "Col. de Destino",
    tbl_schedule: "Programación",
    tbl_status: "Estado",
    status_active: "Activo",
    status_idle: "Inactivo",
    feed_user_activity: "Flujo de Actividad de Usuarios",
    feed_partner_sync: "Sincronización de Base de Datos Socia",
    create_new_collection: "Crear nueva colección...",
    config_tools_list: "Herramientas de MongoDB MCP",
    status_connecting: "Conectando...",
    status_error: "Error al obtener metadatos",
    status_disconnected: "Desconectado",
    auth_failed: "La autenticación falló. Por favor, inténtelo de nuevo.",
    initiating_stream: "[SISTEMA] Iniciando la transmisión de ejecución del agente...",
    query_completed_success: "Consulta completada con éxito. Por favor, revise la consola de registros para ver los detalles.",
    stream_failure: "[ERROR] Fallo en la transmisión: ",
    stream_error_occurred: "Ocurrió un error al transmitir la salida del agente: ",
    preset_list_db_query: "Enumere las bases de datos, enumere las colecciones de la base de datos 'fahem' y recupere las estadísticas de la base de datos.",
    preset_get_stats_query: "Analice las estadísticas de la base de datos 'fahem' y resuma el tamaño de almacenamiento y las métricas de índice.",
    preset_schema_query: "Obtenga el esquema de la colección 'users' dentro de la base de datos 'fahem' y describa sus campos.",
    preset_list_col_query: "Enumere todas las colecciones presentes en la base de datos 'fahem'."
  },
  fr: {
    nav_overview: "Aperçu",
    nav_toolkit: "Outils de l'Agent",
    nav_github: "GitHub",
    nav_signin: "Se Connecter",
    nav_signing_in: "Connexion...",
    welcome_to_fahem: "Bienvenue sur Fahem",
    hero_subtitle: "Console d'assistant IA intelligente alimentée par le kit de développement d'agent Google (ADK) et MongoDB MCP.",
    bullet_1: "Expose des wrappers de schéma MongoDB personnalisés",
    bullet_2: "Transmet les journaux d'exécution en temps réel depuis Python ADK",
    bullet_3: "Diagnostics de base de données entièrement sécurisés et isolés",
    btn_signin_google: "Se connecter avec Google",
    btn_connecting_google: "Connexion à Google...",
    footer_landing: "Console du Projet Fahem • Google Cloud Rapid Agent Hackathon",
    loading_ambient: "Chargement de l'environnement...",
    loading_session: "Vérification de la session...",
    dashboard_title: "Fahem",
    dashboard_subtitle: "Console d'Assistant Google ADK & MongoDB MCP",
    btn_signout: "Se Déconnecter",
    cluster_status: "Cluster MongoDB Atlas : Connecté",
    ask_agent_header: "Demander à l'Agent MongoDB",
    btn_execute: "Exécuter l'Agent",
    btn_executing: "Flux de sortie...",
    btn_clear: "Effacer",
    input_placeholder: "Saisissez une requête (ex. « Analyser les collections et afficher les stats »)",
    logs_header: "Journaux d'Exécution",
    logs_idle: "Console inactive. En attente d'exécution...",
    agent_response_header: "Réponse de l'Agent :",
    metadata_header: "Métadonnées du Cluster",
    meta_active_db: "Base de Données Active",
    meta_collections: "Collections",
    meta_col_names: "Noms des Collections",
    meta_storage_size: "Taille de Stockage",
    config_header: "Configuration de l'Agent",
    config_model: "Modèle Gemini :",
    config_framework: "Framework d'Orchestration :",
    config_mcp: "Connexion MCP :",
    config_tools: "Outils Exposés :",
    footer_dashboard_line1: "Tableau de Bord Fahem | Intégration du Partenaire MongoDB",
    footer_dashboard_line2: "Fonctionne sur Firebase App Hosting • Environnement GCP Secret Manager",
    preset_list_db_title: "Lister les Bases",
    preset_list_db_desc: "Découvre les bases de données disponibles et leurs métriques.",
    preset_get_stats_title: "Stats de la Base",
    preset_get_stats_desc: "Récupère la taille de stockage, les index et les stats pour « fahem ».",
    preset_schema_title: "Analyser le Schéma",
    preset_schema_desc: "Échantillonne la collection « users » pour en déduire le schéma.",
    preset_list_col_title: "Lister les Collections",
    preset_list_col_desc: "Liste toutes les collections de la base de données « fahem ».",
    nav_admin: "Panel d'Admin",
    sourcing_engine_title: "Moteur d'Approvisionnement",
    sourcing_engine_subtitle: "Configurez les pipelines, ingérez les flux bruts et mappez les champs.",
    lbl_pipeline_name: "Nom du Pipeline",
    pipeline_name_placeholder: "ex. Flux de Journaux Utilisateur",
    lbl_ingestion_url: "URL d'Ingestion / Endpoint du Flux",
    ingestion_url_placeholder: "ex. https://api.fahem.app/v1/sourcing-feed",
    lbl_target_collection: "Collection Cible",
    lbl_pipeline_schedule: "Planification du Pipeline",
    schedule_realtime: "Flux en Temps Réel",
    schedule_hourly: "Synchronisation Horaire",
    schedule_daily: "Lot Quotidien",
    schedule_manual: "Déclenchement Manuel",
    btn_create_pipeline: "Créer le Flux de Pipeline",
    btn_test_connection: "Tester la Connexion de l'Endpoint",
    active_feeds_title: "Flux d'Ingestion Actifs",
    tbl_feed_name: "Nom du Flux",
    tbl_target_col: "Col. Cible",
    tbl_schedule: "Planification",
    tbl_status: "Statut",
    status_active: "Actif",
    status_idle: "Inactif",
    feed_user_activity: "Flux d'Activité Utilisateur",
    feed_partner_sync: "Synchronisation de Base de Données Partenaire",
    create_new_collection: "Créer une nouvelle collection...",
    config_tools_list: "Outils de MongoDB MCP",
    status_connecting: "Connexion...",
    status_error: "Erreur lors de la récupération des métadonnées",
    status_disconnected: "Déconnecté",
    auth_failed: "Échec de l'authentification. Veuillez réessayer.",
    initiating_stream: "[SYSTEME] Initialisation du flux d'exécution de l'agent...",
    query_completed_success: "Requête exécutée avec succès. Veuillez vérifier la console des journaux pour plus de détails.",
    stream_failure: "[ERREUR] Échec du flux : ",
    stream_error_occurred: "Une erreur est survenue lors de la diffusion du flux de l'agent : ",
    preset_list_db_query: "Lister les bases de données, lister les collections de la base de données 'fahem' et récupérer les statistiques de la base de données.",
    preset_get_stats_query: "Analyser les statistiques de la base de données 'fahem' et résumer la taille de stockage et les métriques d'index.",
    preset_schema_query: "Obtenir le schéma de collection pour la collection 'users' dans la base de données 'fahem' et décrire ses champs.",
    preset_list_col_query: "Lister toutes les collections présentes dans la base de données 'fahem'."
  },
  de: {
    nav_overview: "Übersicht",
    nav_toolkit: "Agenten-Toolkit",
    nav_github: "GitHub",
    nav_signin: "Anmelden",
    nav_signing_in: "Anmeldung...",
    welcome_to_fahem: "Willkommen bei Fahem",
    hero_subtitle: "Eine intelligente KI-Assistentenkonsole, betrieben durch das Google Agent Development Kit (ADK) und MongoDB MCP.",
    bullet_1: "Stellt benutzerdefinierte MongoDB-Schema-Wrapper bereit",
    bullet_2: "Leitet Ausführungsprotokolle in Echtzeit von Python ADK weiter",
    bullet_3: "Vollständig isolierte und sichere Datenbankdiagnosen",
    btn_signin_google: "Mit Google anmelden",
    btn_connecting_google: "Verbindung mit Google...",
    footer_landing: "Fahem-Projektkonsole • Google Cloud Rapid Agent Hackathon",
    loading_ambient: "Umgebungsdaten werden geladen...",
    loading_session: "Sitzung wird überprüft...",
    dashboard_title: "Fahem",
    dashboard_subtitle: "Google ADK & MongoDB MCP-Assistentenkonsole",
    btn_signout: "Abmelden",
    cluster_status: "MongoDB Atlas Cluster: Verbunden",
    ask_agent_header: "Fragen Sie den MongoDB-Agenten",
    btn_execute: "Agenten ausführen",
    btn_executing: "Ausgabe streamen...",
    btn_clear: "Löschen",
    input_placeholder: "Geben Sie eine Datenbankanfrage ein (z. B. 'Sammlungen analysieren')",
    logs_header: "Ausführungsprotokolle",
    logs_idle: "Konsole im Leerlauf. Warten auf Befehl...",
    agent_response_header: "Antwort des Agenten:",
    metadata_header: "Cluster-Metadaten",
    meta_active_db: "Aktive Datenbank",
    meta_collections: "Sammlungen",
    meta_col_names: "Sammlungsnamen",
    meta_storage_size: "Speichergröße",
    config_header: "Agenten-Kernkonfiguration",
    config_model: "Gemini-Modell:",
    config_framework: "Orchestrierungs-Framework:",
    config_mcp: "MCP-Verbindung:",
    config_tools: "Exponierte Werkzeuge:",
    footer_dashboard_line1: "Fahem-Dashboard | Hackathon MongoDB Track Partner-Integration",
    footer_dashboard_line2: "Läuft auf Firebase App Hosting • Sichere GCP Secret Manager-Umgebung",
    preset_list_db_title: "Datenbanken auflisten",
    preset_list_db_desc: "Erkennt alle verfügbaren Datenbanken und listet deren Metriken auf.",
    preset_get_stats_title: "Datenbankstatistiken",
    preset_get_stats_desc: "Ruft Speichergröße, Indexanzahl und Dokumentenstatistiken ab.",
    preset_schema_title: "Schema analysieren",
    preset_schema_desc: "Analysiert die Sammlung 'users', um deren Schema abzuleiten.",
    preset_list_col_title: "Sammlungen auflisten",
    preset_list_col_desc: "Listet alle Sammlungen in der Datenbank 'fahem' auf.",
    nav_admin: "Admin-Bereich",
    sourcing_engine_title: "Beschaffungs-Engine",
    sourcing_engine_subtitle: "Konfigurieren Sie Pipelines, importieren Sie Datenströme und weisen Sie Felder zu.",
    lbl_pipeline_name: "Pipeline-Name",
    pipeline_name_placeholder: "z. B. Benutzerprotokoll-Feed",
    lbl_ingestion_url: "Erfassungs-URL / Feed-Endpunkt",
    ingestion_url_placeholder: "z. B. https://api.fahem.app/v1/sourcing-feed",
    lbl_target_collection: "Ziel-Sammlung",
    lbl_pipeline_schedule: "Pipeline-Zeitplan",
    schedule_realtime: "Echtzeit-Stream",
    schedule_hourly: "Stündliche Synchronisierung",
    schedule_daily: "Tägliche Stapelverarbeitung",
    schedule_manual: "Manuelle Auslösung",
    btn_create_pipeline: "Pipeline-Feed erstellen",
    btn_test_connection: "Endpunkt-Verbindung testen",
    active_feeds_title: "Aktive Erfassungs-Feeds",
    tbl_feed_name: "Feed-Name",
    tbl_target_col: "Ziel-Sammlung",
    tbl_schedule: "Zeitplan",
    tbl_status: "Status",
    status_active: "Aktiv",
    status_idle: "Bereit",
    feed_user_activity: "Benutzeraktivitäts-Stream",
    feed_partner_sync: "Partner-Datenbank-Synchronisierung",
    create_new_collection: "Neue Sammlung erstellen...",
    config_tools_list: "MongoDB MCP Werkzeuge",
    status_connecting: "Verbinden...",
    status_error: "Fehler beim Abrufen der Metadaten",
    status_disconnected: "Getrennt",
    auth_failed: "Authentifizierung fehlgeschlagen. Bitte versuchen Sie es erneut.",
    initiating_stream: "[SYSTEM] Initiere Ausführungsdatenstrom des Agenten...",
    query_completed_success: "Abfrage erfolgreich abgeschlossen. Bitte überprüfen Sie die Konsolenprotokolle für Details.",
    stream_failure: "[FEHLER] Datenstromfehler: ",
    stream_error_occurred: "Ein Fehler ist beim Streamen der Agentenausgabe aufgetreten: ",
    preset_list_db_query: "Listen Sie die Datenbanken auf, listen Sie die Sammlungen für die Datenbank 'fahem' auf und rufen Sie die Datenbankstatistiken ab.",
    preset_get_stats_query: "Analysieren Sie die Datenbankstatistiken für die Datenbank 'fahem' und fassen Sie die Speichergröße und Indexmetriken zusammen.",
    preset_schema_query: "Rufen Sie das Sammlungsschema für die Sammlung 'users' in der Datenbank 'fahem' ab und beschreiben Sie deren Felder.",
    preset_list_col_query: "Listen Sie alle in der Datenbank 'fahem' vorhandenen Sammlungen auf."
  },
  zh: {
    nav_overview: "概述",
    nav_toolkit: "代理工具包",
    nav_github: "GitHub",
    nav_signin: "登录",
    nav_signing_in: "登录中...",
    welcome_to_fahem: "欢迎使用 Fahem",
    hero_subtitle: "由 Google 代理开发套件 (ADK) 和 MongoDB MCP 工具包提供支持 of 智能 AI 助手控制台。",
    bullet_1: "公开自定义 MongoDB 架构包装器",
    bullet_2: "管道传输来自 Python ADK 的实时执行日志",
    bullet_3: "完全沙箱化且安全的数据库诊断",
    btn_signin_google: "使用 Google 登录",
    btn_connecting_google: "正在连接 Google...",
    footer_landing: "Fahem 项目控制台 • 谷歌云快速代理黑客马拉松",
    loading_ambient: "正在加载环境氛围...",
    loading_session: "正在验证会话...",
    dashboard_title: "Fahem",
    dashboard_subtitle: "Google ADK 和 MongoDB MCP 助手控制台",
    btn_signout: "退出登录",
    cluster_status: "MongoDB Atlas 集群：已连接",
    ask_agent_header: "询问 MongoDB 代理",
    btn_execute: "执行代理",
    btn_executing: "流式输出中...",
    btn_clear: "清空",
    input_placeholder: "输入自定义数据库请求（如“分析集合并显示统计信息”）",
    logs_header: "执行流日志",
    logs_idle: "控制台空闲。等待命令执行...",
    agent_response_header: "代理响应：",
    metadata_header: "集群元数据",
    meta_active_db: "活动数据库",
    meta_collections: "集合数",
    meta_col_names: "集合名称",
    meta_storage_size: "存储大小",
    config_header: "代理核心配置",
    config_model: "Gemini 模型：",
    config_framework: "编排框架：",
    config_mcp: "MCP 连接：",
    config_tools: "公开的工具：",
    footer_dashboard_line1: "Fahem 控制面板 | 黑客马拉松 MongoDB 赛道集成",
    footer_dashboard_line2: "运行在 Firebase App Hosting • 安全的 GCP 密钥管理器环境",
    preset_list_db_title: "列出数据库",
    preset_list_db_desc: "发现所有可用的数据库并列出其基本指标。",
    preset_get_stats_title: "获取数据库统计",
    preset_get_stats_desc: "检索“fahem”的存储大小、索引计数和文档统计。",
    preset_schema_title: "分析架构",
    preset_schema_desc: "从“users”集合中采样文档以推导其架构。",
    preset_list_col_title: "列出集合",
    preset_list_col_desc: "列出“fahem”数据库中的所有集合。",
    nav_admin: "管理控制台",
    sourcing_engine_title: "资源引擎",
    sourcing_engine_subtitle: "配置数据库管道，摄取原始流，并映射文档字段。",
    lbl_pipeline_name: "管道名称",
    pipeline_name_placeholder: "例如：用户日志流",
    lbl_ingestion_url: "摄取 URL / 订阅端点",
    ingestion_url_placeholder: "例如：https://api.fahem.app/v1/sourcing-feed",
    lbl_target_collection: "目标集合",
    lbl_pipeline_schedule: "管道计划",
    schedule_realtime: "实时数据流",
    schedule_hourly: "每小时同步",
    schedule_daily: "每日批处理",
    schedule_manual: "手动触发",
    btn_create_pipeline: "创建管道流",
    btn_test_connection: "测试端点连接",
    active_feeds_title: "活动摄取流",
    tbl_feed_name: "订阅名称",
    tbl_target_col: "目标集合",
    tbl_schedule: "计划",
    tbl_status: "状态",
    status_active: "活动",
    status_idle: "空闲",
    feed_user_activity: "用户活动流",
    feed_partner_sync: "合作伙伴数据库同步",
    create_new_collection: "创建新集合...",
    config_tools_list: "MongoDB MCP 工具集",
    status_connecting: "正在连接...",
    status_error: "获取元数据错误",
    status_disconnected: "已断开连接",
    auth_failed: "身份验证失败。请重试。",
    initiating_stream: "[系统] 正在启动代理执行流...",
    query_completed_success: "查询成功完成。请检查控制台日志以获取详细输出。",
    stream_failure: "[错误] 流传输失败: ",
    stream_error_occurred: "流式传输代理输出时出错: ",
    preset_list_db_query: "列出数据库，列出“fahem”数据库的集合，并检索数据库统计信息。",
    preset_get_stats_query: "分析“fahem”数据库的数据库统计信息，并总结存储大小和索引指标。",
    preset_schema_query: "获取“fahem”数据库中“users”集合的集合架构，并描述其字段。",
    preset_list_col_query: "列出“fahem”数据库中存在的所有集合。"
  },
  it: {
    nav_overview: "Panoramica",
    nav_toolkit: "Toolkit dell'Agente",
    nav_github: "GitHub",
    nav_signin: "Accedi",
    nav_signing_in: "Accesso in corso...",
    welcome_to_fahem: "Benvenuto in Fahem",
    hero_subtitle: "Una console intelligente di assistente IA potenziata a livello di programmazione da Google Agent Development Kit (ADK) e dai toolset MongoDB MCP.",
    bullet_1: "Espone wrapper personalizzati dello schema MongoDB",
    bullet_2: "Invia i log di esecuzione in tempo reale da Python ADK",
    bullet_3: "Diagnostica del database completamente isolata e sicura",
    btn_signin_google: "Accedi con Google",
    btn_connecting_google: "Connessione a Google in corso...",
    footer_landing: "Console del Progetto Fahem • Google Cloud Rapid Agent Hackathon",
    loading_ambient: "Caricamento dell'ambiente circostante...",
    loading_session: "Verifica della sessione...",
    dashboard_title: "Fahem",
    dashboard_subtitle: "Console dell'Assistente Google ADK & MongoDB MCP",
    btn_signout: "Disconnetti",
    cluster_status: "Cluster MongoDB Atlas: Connected",
    ask_agent_header: "Chiedi all'Agente MongoDB",
    btn_execute: "Esegui Agente",
    btn_executing: "Trasmissione output...",
    btn_clear: "Cancella",
    input_placeholder: "Inserisci una richiesta di database personalizzata (es. 'Analizza le collezioni e mostra le statistiche')",
    logs_header: "Log di streaming dell'esecuzione",
    logs_idle: "Console inattiva. In attesa di esecuzione del comando...",
    agent_response_header: "Risposta dell'Agente:",
    metadata_header: "Metadati del Cluster",
    meta_active_db: "Database Attivo",
    meta_collections: "Collezioni",
    meta_col_names: "Nomi delle Collezioni",
    meta_storage_size: "Dimensione dell'archivio",
    config_header: "Configurazione principale dell'Agente",
    config_model: "Modello Gemini:",
    config_framework: "Framework di orchestrazione:",
    config_mcp: "Conessore MCP:",
    config_tools: "Strumenti Esposti:",
    footer_dashboard_line1: "Dashboard della console Fahem | Integrazione partner track MongoDB Hackathon",
    footer_dashboard_line2: "Esecuzione su Firebase App Hosting • Ambiente sicuro di Google Cloud Secret Manager",
    preset_list_db_title: "Elenca Database",
    preset_list_db_desc: "Rileva tutti i database disponibili ed elenca le loro metriche di base.",
    preset_get_stats_title: "Ottieni Statistiche",
    preset_get_stats_desc: "Recupera la dimensione di archiviazione, il numero di indici e le statistiche dei documenti per 'fahem'.",
    preset_schema_title: "Analizza Schema",
    preset_schema_desc: "Campiona i documenti della collezione 'users' per ricavarne lo schema.",
    preset_list_col_title: "Elenca Collezioni",
    preset_list_col_desc: "Elenca tutte le collezioni nel database 'fahem'.",
    nav_admin: "Pannello Admin",
    sourcing_engine_title: "Motore di Sourcing",
    sourcing_engine_subtitle: "Configura pipeline del database, inserisci flussi grezzi e mappa i campi dei documenti.",
    lbl_pipeline_name: "Nome Pipeline",
    pipeline_name_placeholder: "es. Feed dei Log Utente",
    lbl_ingestion_url: "URL di Ingestione / Endpoint del Feed",
    ingestion_url_placeholder: "es. https://api.fahem.app/v1/sourcing-feed",
    lbl_target_collection: "Collezione Target",
    lbl_pipeline_schedule: "Pianificazione Pipeline",
    schedule_realtime: "Stream in Tempo Reale",
    schedule_hourly: "Sincronizzazione Oraria",
    schedule_daily: "Batch Giornaliero",
    schedule_manual: "Attivazione Manuale",
    btn_create_pipeline: "Crea Feed della Pipeline",
    btn_test_connection: "Testa Connessione Endpoint",
    active_feeds_title: "Feed di Ingestione Attivi",
    tbl_feed_name: "Nome Feed",
    tbl_target_col: "Col. Target",
    tbl_schedule: "Pianificazione",
    tbl_status: "Stato",
    status_active: "Attivo",
    status_idle: "Inattivo",
    feed_user_activity: "Stream di Attività Utente",
    feed_partner_sync: "Sincronizzazione Database Partner",
    create_new_collection: "Crea nuova collezione...",
    config_tools_list: "Strumenti MongoDB MCP",
    status_connecting: "Connessione in corso...",
    status_error: "Errore durante il recupero dei metadati",
    status_disconnected: "Disconnesso",
    auth_failed: "Autenticazione fallita. Riprova.",
    initiating_stream: "[SISTEMA] Avvio dello streaming di esecuzione dell'agente...",
    query_completed_success: "Query completata con successo. Controlla la console dei log per i dettagli.",
    stream_failure: "[ERRORE] Errore di trasmissione: ",
    stream_error_occurred: "Si è verificato un errore durante la trasmissione dell'output dell'agente: ",
    preset_list_db_query: "Elenca i database, elenca le collezioni per il database 'fahem' e recupera le statistiche del database.",
    preset_get_stats_query: "Analizza le statistiche del database per il database 'fahem' e riassumi le dimensioni di archiviazione e le metriche dell'indice.",
    preset_schema_query: "Ottieni lo schema della collezione per la collezione 'users' all'interno del database 'fahem' e descrivi i suoi campi.",
    preset_list_col_query: "Elenca tutte le collezioni presenti nel database 'fahem'."
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>("en");

  useEffect(() => {
    const savedLang = localStorage.getItem("fahem_language") as Language;
    if (savedLang && translations[savedLang]) {
      setLanguageState(savedLang);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    if (translations[lang]) {
      setLanguageState(lang);
      localStorage.setItem("fahem_language", lang);
    }
  };

  const t = (key: string): string => {
    return translations[language]?.[key] || translations["en"]?.[key] || key;
  };

  const dir = language === "ar" ? "rtl" : "ltr";

  // Enforce HTML attributes dynamically when language changes
  useEffect(() => {
    document.documentElement.lang = language;
    document.documentElement.dir = dir;
  }, [language, dir]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, dir }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useTranslation() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useTranslation must be used within a LanguageProvider");
  }
  return context;
}
