"use client";

import React, { createContext, useContext, useState, useEffect } from "react";

export type Language = "en" | "ar" | "es" | "fr" | "de" | "zh" | "ja";

export interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  dir: "ltr" | "rtl";
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    nav_overview: "Overview",
    nav_toolkit: "Agent Toolkit",
    nav_github: "GitHub",
    nav_signin: "Sign In",
    nav_signing_in: "Signing In...",
    welcome_to_fahem: "Welcome to Fahem",
    hero_subtitle: "An intelligent AI assistant console programmatically powered by the Google Agent Development Kit (ADK) and MongoDB MCP toolsets.",
    bullet_1: "Exposes custom MongoDB Schema wrappers",
    bullet_2: "Pipes real-time execution logs from Python ADK",
    bullet_3: "Fully sandboxed and secure database diagnostics",
    btn_signin_google: "Sign in with Google",
    btn_connecting_google: "Connecting to Google...",
    footer_landing: "Fahem Project Console • Google Cloud Rapid Agent Hackathon",
    loading_ambient: "Loading ambient environment...",
    loading_session: "Verifying session...",
    dashboard_title: "Fahem",
    dashboard_subtitle: "Google ADK & MongoDB MCP Assistant Console",
    btn_signout: "Sign Out",
    cluster_status: "MongoDB Atlas Cluster: Connected",
    ask_agent_header: "Ask the MongoDB Agent",
    btn_execute: "Execute Agent",
    btn_executing: "Streaming Output...",
    btn_clear: "Clear",
    input_placeholder: "Enter a custom database request (e.g. 'Analyze collections and show stats for fahem database')",
    logs_header: "Execution Stream Logs",
    logs_idle: "Console idle. Awaiting command execution...",
    agent_response_header: "Agent Response:",
    metadata_header: "Cluster Metadata",
    meta_active_db: "Active Database",
    meta_collections: "Collections",
    meta_col_names: "Collection Names",
    meta_storage_size: "Storage Size",
    config_header: "Agent Core Config",
    config_model: "Gemini Model:",
    config_framework: "Orchestrator Framework:",
    config_mcp: "MCP Connection:",
    config_tools: "Exposed Tools:",
    footer_dashboard_line1: "Fahem Console Dashboard | Hackathon MongoDB Track Partner Integration",
    footer_dashboard_line2: "Running on Firebase App Hosting • Secure Google Cloud Secret Manager Environment",
    preset_list_db_title: "List Databases",
    preset_list_db_desc: "Discovers all available databases and lists their basic metrics.",
    preset_get_stats_title: "Get Database Stats",
    preset_get_stats_desc: "Retrieves storage size, index counts, and document stats for 'fahem'.",
    preset_schema_title: "Analyze Schema",
    preset_schema_desc: "Samples documents from 'users' collection to derive its schema.",
    preset_list_col_title: "List Collections",
    preset_list_col_desc: "Lists all collections in the 'fahem' database."
  },
  ar: {
    nav_overview: "نظرة عامة",
    nav_toolkit: "أدوات الوكيل",
    nav_github: "جيت هاب",
    nav_signin: "تسجيل الدخول",
    nav_signing_in: "جاري الدخول...",
    welcome_to_fahem: "مرحباً بكم في فهم",
    hero_subtitle: "منصة ذكاء اصطناعي تفاعلية مدعومة برمجياً بحزمة تطوير الوكيل من جوجل (ADK) وأدوات بروتوكول سياق نموذج MongoDB (MCP).",
    bullet_1: "يعرض مغلفات مخصصة لمخطط قاعدة بيانات MongoDB",
    bullet_2: "ينقل سجلات التنفيذ الفورية من Python ADK مباشرة",
    bullet_3: "تشخيصات قاعدة بيانات معزولة تماماً وآمنة للغاية",
    btn_signin_google: "تسجيل الدخول باستخدام جوجل",
    btn_connecting_google: "جاري الاتصال بجوجل...",
    footer_landing: "لوحة تحكم مشروع فهم • هاكاثون وكلاء جوجل السحابي السريع",
    loading_ambient: "جاري تحميل البيئة التفاعلية...",
    loading_session: "جاري التحقق من الجلسة...",
    dashboard_title: "فهم",
    dashboard_subtitle: "لوحة تحكم مساعد جوجل ADK وقاعدة بيانات MongoDB MCP",
    btn_signout: "تسجيل الخروج",
    cluster_status: "عنقود MongoDB Atlas: متصل",
    ask_agent_header: "اسأل وكيل MongoDB",
    btn_execute: "تشغيل الوكيل",
    btn_executing: "جاري بث المخرجات...",
    btn_clear: "مسح",
    input_placeholder: "أدخل طلباً مخصصاً لقاعدة البيانات (مثال: 'حلل المجموعات واعرض الإحصائيات لقاعدة فهم')",
    logs_header: "سجلات بث التنفيذ الفوري",
    logs_idle: "منصة التحكم في حالة انتظار. في انتظار تشغيل الأوامر...",
    agent_response_header: "إجابة الوكيل:",
    metadata_header: "البيانات الوصفية للعنقود",
    meta_active_db: "قاعدة البيانات النشطة",
    meta_collections: "المجموعات",
    meta_col_names: "أسماء المجموعات",
    meta_storage_size: "حجم التخزين",
    config_header: "الإعدادات الأساسية للوكيل",
    config_model: "نموذج Gemini:",
    config_framework: "إطار عمل التنسيق:",
    config_mcp: "اتصال MCP:",
    config_tools: "الأدوات المعروضة:",
    footer_dashboard_line1: "لوحة تحكم فهم | تكامل شريك مسار MongoDB في الهاكاثون",
    footer_dashboard_line2: "يعمل على استضافة تطبيقات Firebase • بيئة آمنة لإدارة أسرار Google Cloud",
    preset_list_db_title: "سرد قواعد البيانات",
    preset_list_db_desc: "يكتشف جميع قواعد البيانات المتاحة ويعرض مقاييسها الأساسية.",
    preset_get_stats_title: "إحصائيات قاعدة البيانات",
    preset_get_stats_desc: "يسترجع حجم التخزين، وأعداد الفهارس، وإحصائيات المستندات لقاعدة 'فهم'.",
    preset_schema_title: "تحليل المخطط",
    preset_schema_desc: "يأخذ عينات من المستندات من مجموعة 'المستخدمين' لاستنتاج مخططها.",
    preset_list_col_title: "سرد المجموعات",
    preset_list_col_desc: "يسرد جميع المجموعات في قاعدة بيانات 'فهم'."
  },
  es: {
    nav_overview: "Resumen",
    nav_toolkit: "Herramientas",
    nav_github: "GitHub",
    nav_signin: "Iniciar Sesión",
    nav_signing_in: "Conectando...",
    welcome_to_fahem: "Bienvenido a Fahem",
    hero_subtitle: "Consola de asistente de IA inteligente potenciada programáticamente por Google Agent Development Kit (ADK) y MongoDB MCP.",
    bullet_1: "Expone contenedores de esquema personalizados de MongoDB",
    bullet_2: "Transmite registros de ejecución en tiempo real desde Python ADK",
    bullet_3: "Diagnósticos de base de datos seguros en entorno aislado",
    btn_signin_google: "Iniciar sesión con Google",
    btn_connecting_google: "Conectando a Google...",
    footer_landing: "Consola de Fahem • Google Cloud Rapid Agent Hackathon",
    loading_ambient: "Cargando entorno ambiental...",
    loading_session: "Verificando sesión...",
    dashboard_title: "Fahem",
    dashboard_subtitle: "Consola de Asistente Google ADK y MongoDB MCP",
    btn_signout: "Cerrar Sesión",
    cluster_status: "Clúster MongoDB Atlas: Conectado",
    ask_agent_header: "Pregunta al Agente MongoDB",
    btn_execute: "Ejecutar Agente",
    btn_executing: "Transmitiendo...",
    btn_clear: "Limpiar",
    input_placeholder: "Ingrese una solicitud personalizada (ej. 'Analizar colecciones y mostrar estadísticas')",
    logs_header: "Registros de Ejecución",
    logs_idle: "Consola inactiva. Esperando comandos...",
    agent_response_header: "Respuesta del Agente:",
    metadata_header: "Metadatos del Clúster",
    meta_active_db: "Base de Datos Activa",
    meta_collections: "Colecciones",
    meta_col_names: "Nombres de Colecciones",
    meta_storage_size: "Tamaño de Almacenamiento",
    config_header: "Configuración del Agente",
    config_model: "Modelo Gemini:",
    config_framework: "Marco de Orquestación:",
    config_mcp: "Conexión MCP:",
    config_tools: "Herramientas Expuestas:",
    footer_dashboard_line1: "Panel de Fahem | Integración del Socio del Track MongoDB",
    footer_dashboard_line2: "Ejecutándose en Firebase App Hosting • Entorno Seguro de GCP Secret Manager",
    preset_list_db_title: "Listar Bases de Datos",
    preset_list_db_desc: "Descubre las bases de datos disponibles y sus métricas básicas.",
    preset_get_stats_title: "Obtener Estadísticas",
    preset_get_stats_desc: "Recupera tamaño de almacenamiento, índices y estadísticas de 'fahem'.",
    preset_schema_title: "Analizar Esquema",
    preset_schema_desc: "Muestrea documentos de la colección 'users' para derivar su esquema.",
    preset_list_col_title: "Listar Colecciones",
    preset_list_col_desc: "Enumera todas las colecciones en la base de datos 'fahem'."
  },
  fr: {
    nav_overview: "Aperçu",
    nav_toolkit: "Outils de l'Agent",
    nav_github: "GitHub",
    nav_signin: "Se Connecter",
    nav_signing_in: "Connexion...",
    welcome_to_fahem: "Bienvenue sur Fahem",
    hero_subtitle: "Console d'assistant IA intelligente alimentée par le kit de développement d'agent Google (ADK) et MongoDB MCP.",
    bullet_1: "Expose des wrappers de schéma MongoDB personnalisés",
    bullet_2: "Transmet les journaux d'exécution en temps réel depuis Python ADK",
    bullet_3: "Diagnostics de base de données entièrement sécurisés et isolés",
    btn_signin_google: "Se connecter avec Google",
    btn_connecting_google: "Connexion à Google...",
    footer_landing: "Console du Projet Fahem • Google Cloud Rapid Agent Hackathon",
    loading_ambient: "Chargement de l'environnement...",
    loading_session: "Vérification de la session...",
    dashboard_title: "Fahem",
    dashboard_subtitle: "Console d'Assistant Google ADK & MongoDB MCP",
    btn_signout: "Se Déconnecter",
    cluster_status: "Cluster MongoDB Atlas : Connecté",
    ask_agent_header: "Demander à l'Agent MongoDB",
    btn_execute: "Exécuter l'Agent",
    btn_executing: "Flux de sortie...",
    btn_clear: "Effacer",
    input_placeholder: "Saisissez une requête (ex. « Analyser les collections et afficher les stats »)",
    logs_header: "Journaux d'Exécution",
    logs_idle: "Console inactive. En attente d'exécution...",
    agent_response_header: "Réponse de l'Agent :",
    metadata_header: "Métadonnées du Cluster",
    meta_active_db: "Base de Données Active",
    meta_collections: "Collections",
    meta_col_names: "Noms des Collections",
    meta_storage_size: "Taille de Stockage",
    config_header: "Configuration de l'Agent",
    config_model: "Modèle Gemini :",
    config_framework: "Framework d'Orchestration :",
    config_mcp: "Connexion MCP :",
    config_tools: "Outils Exposés :",
    footer_dashboard_line1: "Tableau de Bord Fahem | Intégration du Partenaire MongoDB",
    footer_dashboard_line2: "Fonctionne sur Firebase App Hosting • Environnement GCP Secret Manager",
    preset_list_db_title: "Lister les Bases",
    preset_list_db_desc: "Découvre les bases de données disponibles et leurs métriques.",
    preset_get_stats_title: "Stats de la Base",
    preset_get_stats_desc: "Récupère la taille de stockage, les index et les stats pour « fahem ».",
    preset_schema_title: "Analyser le Schéma",
    preset_schema_desc: "Échantillonne la collection « users » pour en déduire le schéma.",
    preset_list_col_title: "Lister les Collections",
    preset_list_col_desc: "Liste toutes les collections de la base de données « fahem »."
  },
  de: {
    nav_overview: "Übersicht",
    nav_toolkit: "Agenten-Toolkit",
    nav_github: "GitHub",
    nav_signin: "Anmelden",
    nav_signing_in: "Anmeldung...",
    welcome_to_fahem: "Willkommen bei Fahem",
    hero_subtitle: "Eine intelligente KI-Assistentenkonsole, betrieben durch das Google Agent Development Kit (ADK) und MongoDB MCP.",
    bullet_1: "Stellt benutzerdefinierte MongoDB-Schema-Wrapper bereit",
    bullet_2: "Leitet Ausführungsprotokolle in Echtzeit von Python ADK weiter",
    bullet_3: "Vollständig isolierte und sichere Datenbankdiagnosen",
    btn_signin_google: "Mit Google anmelden",
    btn_connecting_google: "Verbindung mit Google...",
    footer_landing: "Fahem-Projektkonsole • Google Cloud Rapid Agent Hackathon",
    loading_ambient: "Umgebungsdaten werden geladen...",
    loading_session: "Sitzung wird überprüft...",
    dashboard_title: "Fahem",
    dashboard_subtitle: "Google ADK & MongoDB MCP-Assistentenkonsole",
    btn_signout: "Abmelden",
    cluster_status: "MongoDB Atlas Cluster: Verbunden",
    ask_agent_header: "Fragen Sie den MongoDB-Agenten",
    btn_execute: "Agenten ausführen",
    btn_executing: "Ausgabe streamen...",
    btn_clear: "Löschen",
    input_placeholder: "Geben Sie eine Datenbankanfrage ein (z. B. 'Sammlungen analysieren')",
    logs_header: "Ausführungsprotokolle",
    logs_idle: "Konsole im Leerlauf. Warten auf Befehl...",
    agent_response_header: "Antwort des Agenten:",
    metadata_header: "Cluster-Metadaten",
    meta_active_db: "Aktive Datenbank",
    meta_collections: "Sammlungen",
    meta_col_names: "Sammlungsnamen",
    meta_storage_size: "Speichergröße",
    config_header: "Agenten-Kernkonfiguration",
    config_model: "Gemini-Modell:",
    config_framework: "Orchestrierungs-Framework:",
    config_mcp: "MCP-Verbindung:",
    config_tools: "Exponierte Werkzeuge:",
    footer_dashboard_line1: "Fahem-Dashboard | Hackathon MongoDB Track Partner-Integration",
    footer_dashboard_line2: "Läuft auf Firebase App Hosting • Sichere GCP Secret Manager-Umgebung",
    preset_list_db_title: "Datenbanken auflisten",
    preset_list_db_desc: "Erkennt alle verfügbaren Datenbanken und listet deren Metriken auf.",
    preset_get_stats_title: "Datenbankstatistiken",
    preset_get_stats_desc: "Ruft Speichergröße, Indexanzahl und Dokumentenstatistiken ab.",
    preset_schema_title: "Schema analysieren",
    preset_schema_desc: "Analysiert die Sammlung 'users', um deren Schema abzuleiten.",
    preset_list_col_title: "Sammlungen auflisten",
    preset_list_col_desc: "Listet alle Sammlungen in der Datenbank 'fahem' auf."
  },
  zh: {
    nav_overview: "概述",
    nav_toolkit: "代理工具包",
    nav_github: "GitHub",
    nav_signin: "登录",
    nav_signing_in: "登录中...",
    welcome_to_fahem: "欢迎使用 Fahem",
    hero_subtitle: "由 Google 代理开发套件 (ADK) 和 MongoDB MCP 工具包提供支持的智能 AI 助手控制台。",
    bullet_1: "公开自定义 MongoDB 架构包装器",
    bullet_2: "管道传输来自 Python ADK 的实时执行日志",
    bullet_3: "完全沙箱化且安全的数据库诊断",
    btn_signin_google: "使用 Google 登录",
    btn_connecting_google: "正在连接 Google...",
    footer_landing: "Fahem 项目控制台 • 谷歌云快速代理黑客马拉松",
    loading_ambient: "正在加载环境氛围...",
    loading_session: "正在验证会话...",
    dashboard_title: "Fahem",
    dashboard_subtitle: "Google ADK 和 MongoDB MCP 助手控制台",
    btn_signout: "退出登录",
    cluster_status: "MongoDB Atlas 集群：已连接",
    ask_agent_header: "询问 MongoDB 代理",
    btn_execute: "执行代理",
    btn_executing: "流式输出中...",
    btn_clear: "清空",
    input_placeholder: "输入自定义数据库请求（如“分析集合并显示统计信息”）",
    logs_header: "执行流日志",
    logs_idle: "控制台空闲。等待命令执行...",
    agent_response_header: "代理响应：",
    metadata_header: "集群元数据",
    meta_active_db: "活动数据库",
    meta_collections: "集合数",
    meta_col_names: "集合名称",
    meta_storage_size: "存储大小",
    config_header: "代理核心配置",
    config_model: "Gemini 模型：",
    config_framework: "编排框架：",
    config_mcp: "MCP 连接：",
    config_tools: "公开的工具：",
    footer_dashboard_line1: "Fahem 控制面板 | 黑客马拉松 MongoDB 赛道集成",
    footer_dashboard_line2: "运行在 Firebase App Hosting • 安全的 GCP 密钥管理器环境",
    preset_list_db_title: "列出数据库",
    preset_list_db_desc: "发现所有可用的数据库并列出其基本指标。",
    preset_get_stats_title: "获取数据库统计",
    preset_get_stats_desc: "检索“fahem”的存储大小、索引计数和文档统计。",
    preset_schema_title: "分析架构",
    preset_schema_desc: "从“users”集合中采样文档以推导其架构。",
    preset_list_col_title: "列出集合",
    preset_list_col_desc: "列出“fahem”数据库中的所有集合。"
  },
  ja: {
    nav_overview: "概要",
    nav_toolkit: "エージェントツールキット",
    nav_github: "GitHub",
    nav_signin: "サインイン",
    nav_signing_in: "サインイン中...",
    welcome_to_fahem: "Fahemへようこそ",
    hero_subtitle: "Google Agent Development Kit (ADK) および MongoDB MCP ツールセットによって動く、インテリジェントな AI アシスタントコンソール。",
    bullet_1: "カスタム MongoDB スキーマ・ラッパーの公開",
    bullet_2: "Python ADK からのリアルタイム実行ログのパイプ処理",
    bullet_3: "完全にサンドボックス化された安全なデータベース診断",
    btn_signin_google: "Googleでサインイン",
    btn_connecting_google: "Googleに接続中...",
    footer_landing: "Fahem プロジェクトコンソール • Google Cloud Rapid Agent ハッカソン",
    loading_ambient: "アンビエント環境を読み込み中...",
    loading_session: "セッションを検証中...",
    dashboard_title: "Fahem",
    dashboard_subtitle: "Google ADK ＆ MongoDB MCP アシスタントコンソール",
    btn_signout: "サインアウト",
    cluster_status: "MongoDB Atlas クラスター: 接続済み",
    ask_agent_header: "MongoDBエージェントに質問する",
    btn_execute: "エージェントを実行",
    btn_executing: "出力をストリーミング中...",
    btn_clear: "クリア",
    input_placeholder: "カスタムデータベース要求を入力します（例：「コレクションを分析する」）",
    logs_header: "実行ストリームログ",
    logs_idle: "コンソールはアイドル状態です。コマンドの実行を待っています...",
    agent_response_header: "エージェントの応答:",
    metadata_header: "クラスタメタデータ",
    meta_active_db: "アクティブなデータベース",
    meta_collections: "コレクション数",
    meta_col_names: "コレクション名",
    meta_storage_size: "ストレージサイズ",
    config_header: "エージェントコア構成",
    config_model: "Geminiモデル:",
    config_framework: "オーケストレーターフレームワーク:",
    config_mcp: "MCP接続:",
    config_tools: "公開されているツール:",
    footer_dashboard_line1: "Fahem ダッシュボード | ハッカソン MongoDB トラック統合",
    footer_dashboard_line2: "Firebase App Hosting で実行中 • 安全な GCP Secret Manager 環境",
    preset_list_db_title: "データベース一覧",
    preset_list_db_desc: "利用可能なすべてのデータベースを検出し、その基本メトリクスを一覧表示します。",
    preset_get_stats_title: "データベース統計",
    preset_get_stats_desc: "「fahem」のストレージサイズ、インデックス数、ドキュメント統計を取得します。",
    preset_schema_title: "スキーマ分析",
    preset_schema_desc: "「users」コレクションからドキュメントをサンプリングしてスキーマを導出します。",
    preset_list_col_title: "コレクション一覧",
    preset_list_col_desc: "「fahem」データベース内のすべてのコレクションを一覧表示します。"
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>("en");

  useEffect(() => {
    const savedLang = localStorage.getItem("fahem_language") as Language;
    if (savedLang && translations[savedLang]) {
      setLanguageState(savedLang);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    if (translations[lang]) {
      setLanguageState(lang);
      localStorage.setItem("fahem_language", lang);
    }
  };

  const t = (key: string): string => {
    return translations[language]?.[key] || translations["en"]?.[key] || key;
  };

  const dir = language === "ar" ? "rtl" : "ltr";

  // Enforce HTML attributes dynamically when language changes
  useEffect(() => {
    document.documentElement.lang = language;
    document.documentElement.dir = dir;
  }, [language, dir]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, dir }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useTranslation() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useTranslation must be used within a LanguageProvider");
  }
  return context;
}
